//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.tbl_setExam = new HashSet<tbl_setExam>();
        }
    
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string std_password { get; set; }
        public string std_image { get; set; }
    
        public virtual ICollection<tbl_setExam> tbl_setExam { get; set; }
    }
}
