//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_admin
    {
        public int ad_id { get; set; }
        [Display(Name = "Admin Name")]
        [Required(ErrorMessage = "*")]
        public string ad_name { get; set; }
        [Display(Name = "Admin Password")]
        [Required(ErrorMessage = "*")]
        public string ad_pass { get; set; }
    }
}
