//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_category
    {
        public tbl_category()
        {
            this.tbl_questions = new HashSet<tbl_questions>();
        }
    
        public int cat_id { get; set; }
        [Display(Name ="Subject")]
        [Required(ErrorMessage ="*")]
        public string cat_name { get; set; }
        public Nullable<int> cat_fk_ad_id { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual ICollection<tbl_questions> tbl_questions { get; set; }
    }
}
