//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_setExam
    {
        public int examId { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<int> exam_fk_stu { get; set; }
        public string exam_name { get; set; }
    
        public virtual student student { get; set; }
    }
}
